language: dart
dart:
  - dev

stages:
  - format
  - analyze
  - test
  - coverage

jobs:
  include:
    - stage: format
      script: ./tool/travis/task.sh dartfmt

    - stage: analyze
      script: ./tool/travis/task.sh dartanalyzer

    - stage: test
      script: ./tool/travis/task.sh test

    - stage: coverage
      install:
        - gem install coveralls-lcov
      script: ./tool/travis/coverage.sh

cache:
  directories:
    - $HOME/.pub-cache
