name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 5.0.0
homepage: https://github.com/luanpotter/ordered_set

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  test: ^1.17.10
  dart_code_metrics: ^4.6.0
  dartdoc: ^4.1.0
  coverage: ^1.0.3
  flame_lint: ^0.0.1
