name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 5.0.1
homepage: https://github.com/luanpotter/ordered_set

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  coverage: ^1.6.3
  dartdoc: ^6.3.0
  flame_lint: ^1.1.0
  test: ^1.24.6
