name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 1.1.0
homepage: https://github.com/luanpotter/ordered_set
author: Luan Nico <luannico27@gmail.com>

environment:
  sdk: '>=2.0.0-dev.54.0 <2.0.0'

dev_dependencies:
  test: ^0.12.38
