name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 6.0.1
homepage: https://github.com/bluefireteam/ordered_set
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: '>=2.14.0 <4.0.0'

dev_dependencies:
  coverage: ^1.8.0
  dartdoc: ^8.0.9+1
  flame_lint: ^1.2.0
  test: ^1.25.7
