name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 4.0.0
homepage: https://github.com/luanpotter/ordered_set

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
  dart_code_metrics: ^3.2.2
  dartdoc: ^0.42.0
  coverage: ^1.0.3
