name: ordered_set
description: A simple implementation for an ordered set
version: 0.1.0
homepage: https://github.com/luanpotter/ordered_set
author: Luan Nico <luannico27@gmail.com>

environment:
  sdk: '>=2.0.0-dev.54.0 <2.0.0'

dev_dependencies:
  test: ^0.12.38
