name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 6.0.0
homepage: https://github.com/bluefireteam/ordered_set

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  coverage: ^1.7.2
  dartdoc: ^8.0.8
  flame_lint: ^1.1.2
  test: ^1.25.3
