name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 3.0.0-nullsafety.0
homepage: https://github.com/luanpotter/ordered_set

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
  dart_code_metrics: ^2.4.0
  dartdoc: ^0.39.0
  coverage: ^0.14.2
