name: ordered_set
description: A simple implementation of an Ordered Set for Dart that allows multiple items with the same priority.
version: 8.0.0
homepage: https://github.com/bluefireteam/ordered_set
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - data-structures
  - collections
  - ordered-set

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  benchmark_harness: ^2.3.1
  coverage: ^1.13.1
  dartdoc: ^8.3.3
  flame_lint: ^1.3.0
  test: ^1.26.2
