name: Benchmark

on: [pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: dart-lang/setup-dart@v1
    - run: dart pub get

    - uses: luanpotter/dart-benchmark-action@v0.1.10
      with:
        paths: "."
        ignore-tag: "no-benchmark"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
