name: cicd

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # BEGIN LINTING STAGE
  dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: echo $PATH
      - run: ls /opt/hostedtoolcache/
      - run: ls /opt/hostedtoolcache/flutter/
      - run: ls /opt/hostedtoolcache/flutter/1.26.0-17.6.pre-beta/
      - run: ls /opt/hostedtoolcache/flutter/1.26.0-17.6.pre-beta/x64/bin/cache/dart-sdk/bin
      - run: ./scripts/dartdoc.sh

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: ./scripts/format.sh

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: ./scripts/analyze.sh
  # END LINTING STAGE

  # BEGIN TESTING STAGE
  test:
    needs: [dartdoc, format, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: dart test

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: ./scripts/coverage.sh
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  # END TESTING STAGE
