name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # BEGIN LINTING STAGE
  dartdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get # make sure flutter downloads dart for us
      - run: ./scripts/dartdoc.sh

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get # make sure flutter downloads dart for us
      - run: ./scripts/format.sh

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get # make sure flutter downloads dart for us
      - run: ./scripts/analyze.sh
  # END LINTING STAGE

  # BEGIN TESTING STAGE
  test:
    needs: [dartdoc, format, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get # make sure flutter downloads dart for us
      - run: ./scripts/coverage.sh
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  # END TESTING STAGE
